# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0002_auto_20170316_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floatvalue',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='intvalue',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pymeasureknowledgesystem',
            name='property_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pymeasureknowledgesystem',
            name='property_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pymeasureknowledgesystem',
            name='units',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='textvalue',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
