# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0003_auto_20170316_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='float_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.FloatValue'),
        ),
        migrations.AlterField(
            model_name='description',
            name='int_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.IntValue'),
        ),
        migrations.AlterField(
            model_name='description',
            name='pyMeasure_ks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.pyMeasureKnowledgeSystem'),
        ),
        migrations.AlterField(
            model_name='description',
            name='text_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.TextValue'),
        ),
        migrations.AlterField(
            model_name='pymeasureknowledgesystem',
            name='property',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
