# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('fitting', '0004_auto_20170316_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pymeasureknowledgesystem',
            old_name='units',
            new_name='property_units',
        ),
        migrations.RemoveField(
            model_name='project',
            name='groups',
        ),
        migrations.AddField(
            model_name='project',
            name='project_groups',
            field=models.ManyToManyField(null=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='descriptions',
            field=models.ManyToManyField(null=True, to='fitting.Description'),
        ),
    ]
