# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0005_auto_20170317_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='location',
            field=models.CharField(default=None, max_length=500, verbose_name='Location on Disk'),
        ),
    ]
