# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0008_auto_20170317_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='float_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.FloatValue'),
        ),
        migrations.AlterField(
            model_name='description',
            name='int_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.IntValue'),
        ),
        migrations.AlterField(
            model_name='description',
            name='pyMeasure_ks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.pyMeasureKnowledgeSystem'),
        ),
        migrations.AlterField(
            model_name='description',
            name='text_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitting.TextValue'),
        ),
    ]
