# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0009_auto_20170317_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitraryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.TextField(verbose_name='String data')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='descriptions',
            field=models.ManyToManyField(blank=True, null=True, to='fitting.Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall',
            field=models.TextField(blank=True, null=True),
        ),
    ]
