# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0010_auto_20170413_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_content', models.TextField()),
                ('measurement_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_content', models.TextField()),
                ('state_name', models.CharField(max_length=500)),
            ],
        ),
    ]
