# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0011_measurement_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionData',
            fields=[
                ('sample_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=10000)),
                ('bowtie', models.BooleanField()),
                ('v_min', models.FloatField()),
                ('v_max', models.FloatField()),
                ('number_points', models.IntegerField()),
                ('plot_format', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='functiondatamodel',
            name='sample_name',
            field=models.CharField(default='default_name', max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='functiondatamodel',
            name='id',
            field=models.IntegerField(),
        ),
    ]
